language: node_js
node_js:
  - "node"

notifications:
  email: false

branches:
  only:
  - master

script:
  - npm test

after_success:
  - bash <(curl -s https://codecov.io/bash) -t c4742c4b-5945-42d3-92a6-38e86cac9538

services:
  - mysql

before_install:
  - cd NODE-SERVER
  - mysql -e 'CREATE DATABASE test;'