language: node_js
sudo: false
node_js:
  - "node"

notifications:
  email: false

branches:
  only:
  - master

script:
  - npm tst

after_success:
  - codecov

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE test;'
  - mysql -u root test < SQL/server.sql
  - npm install -g codecov